#For deployment to stage
spring:
  application:
    name: STAGE-DOCUMENT-SERVICE

app:
#  application:
#    name: INVESTOR-SERVICE
  storage:
    blobService: https://devstoragesi.blob.core.windows.net
    azureBlobSasToken: ?sv=2022-11-02&ss=bfqt&srt=sco&sp=rwdlacupiyx&se=2025-01-01T01:40:43Z&st=2024-01-01T07:40:43Z&spr=https&sig=Imx0r2doZ9Y1nCxnq56yAiKjA%2B0B7kf66XqO%2FvYHIUc%3D
    container: stage
  mongoBaseUrl: https://mongo-stage.azurewebsites.net/productsapi

multitenancy:
  saas:
    datasource:
#      connectionString: Database=stageflex; Data Source=stageflex.mysql.database.azure.com; User Id=dataadmin; Password=solaRadmiN3246
      connectionString: Database=stgdbsi; Data Source=stgdbsi.mysql.database.azure.com; User Id=dataadmin; Password=solaRadmiN3246
      driverClassName: com.mysql.cj.jdbc.Driver
      connectionTimeout: 30000
#      maxPoolSize: 20          # This is set dynamically, DynamicConnectionParams.MAX_POOL_SIZE
#      idleTimeout: 30000       # When running as a fixed-size pool (default) the idleTimeout has no effect.
#      minIdle: 5               # Makes it fixed pool size (recommended by HickariCP). When minimumIdle is not defined it defaults to maximumPoolSize.
#      maxLifetime: 28800000    # This is set dynamically, DynamicConnectionParams.MAX_LIFE_TIME
      leakDetectionThreshold: 300000
      poolName: saas-schema-connection-pool
      effectiveSpindleCount: 0

#CSV tenant schema list
tenantSchemas:
  update: false

swagger:
  host: ${BEHOST}
